### ISSUE TITLE
Support for File Uploads

### ISSUE THREAD

**Issue by chattes** [dai-shi/social-cms-backend#18]
First of all thanks for this neat little module.
I was tearing my hair trying to make wordpress restful. 

As mentioned , although I have not tried yet, was wondering if I can upload Files and Images in Post.

Cheers!

**Comment by dai-shi** [comment]
@chattes Thanks for your feedback.
This library does not intend to store files and does not support MongoDB GridFS.
However, if the file content is small, you could embed it in a JSON document.
Otherwise, or if you want to download a file content by a simple HTTP GET instead of JSON,
I'd recommend to store files somewhere in cloud like S3, and put the URL in a JSON document.

Hope it helps.

Please feel free to reopen this issue for further discussions.

**Comment by chattes** [comment]
Yes thats the idea, basically to upload file to S3 and store a link. Thanks ..
